kumuluzee:
  name: requests-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  discovery:
    etcd:
      hosts: http://localhost:2379
    ttl: 30
    ping-interval: 5
  datasources:
    - jndi-name: jdbc/RequestsDB
      connection-url: jdbc:postgresql://localhost:5432/requests
      username: dbuser
      password: postgres
  config:
    etcd:
      hosts: http://localhost:2379
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/RequestsDB
    metrics:
      web-instrumentation:
        - name: requests-endpoint
          url-pattern: /v1/requests/*
  openapi-mp:
    enabled: true
    servlet:
      mapping: /uniborrow-requests/openapi
    ui:
      enabled: true
      mapping: /uniborrow-requests/openapi/ui
      specification-server: http://35.223.79.242
    dev:
      scan-libraries:
        - requests-models
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                            <Configuration name="comments">
                                <Appenders>
                                    <Console name="console" target="SYSTEM_OUT">
                                        <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                    </Console>
                                    <Socket name="logstash" host="252bc561-0bda-442f-97f3-ba3d8b1a720d-ls.logit.io"
                                    port="18623" protocol="udp">
                                        <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                    </Socket>
                                </Appenders>
                                <Loggers>
                                    <!-- Default logger -->
                                    <Root level="all">
                                        <AppenderRef ref="console" level="info" />
                                        <AppenderRef ref="logstash" level="trace" />
                                    </Root>
                                </Loggers>
                            </Configuration>'
rest-properties:
  maintenance-mode: false
  broken: false