kumuluzee:
  name: requests-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  discovery:
    etcd:
      hosts: http://localhost:2379
    ttl: 30
    ping-interval: 5
  datasources:
    - jndi-name: jdbc/RequestsDB
      connection-url: jdbc:postgresql://localhost:5432/requests
      username: dbuser
      password: postgres
  config:
    etcd:
      hosts: http://localhost:2379
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/RequestsDB
    metrics:
      web-instrumentation:
        - name: requests-endpoint
          url-pattern: /v1/requests/*
rest-properties:
  maintenance-mode: false
  broken: false